# provision.yml

---
- name: Provision EVM Nodes
  hosts: evm_nodes
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - python3-pip  # Example: Install required packages

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
        state: present
      loop:
        - 104047360514.dkr.ecr.eu-central-1.amazonaws.com/go-ethereum:latest
        - 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkvem-node:latest
        - 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-prover:latest
        - 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-contracts:latest
  # Replace with your Docker image names

    - name: Create Ethereum Data Directory
      file:
        path: /var/ethereum-data
        state: directory
      become: yes
  
    - name: Configure Ethereum Nodes
      command: |
        docker run -d --name eth_node_{{ inventory_hostname }} \
          -v /path/to/data:/data 104047360514.dkr.ecr.eu-central-1.amazonaws.com/go-ethereum:latest \
          --datadir /data \
          --networkid 1234 \
          --rpc \
          --rpcaddr "0.0.0.0" \
          --rpcport 8545
      async: 3600
      poll: 0
