name: EVM Testnet Workflow

on:
  workflow_dispatch:
  
jobs:
  deploy-testnet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Pull Docker Images
      run: |
        docker pull 104047360514.dkr.ecr.eu-central-1.amazonaws.com/go-ethereum:latest
        docker pull 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-node:latest
        docker pull 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-contracts:latest

    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-central-1
        aws configure set default.output json

    - name: Set up Cloud Environment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-central-1
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    - name: Generate Dynamic Inventory
      working-directory: terraform
      run: |
        chmod +x dynamic-inventory-script.py
        ./dynamic-inventory-script.py > dynamic_inventory.json
        cat dynamic_inventory.json

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose your preferred Python version

    - name: Install Ansible
      run: pip install ansible
    
    - name: Run Ansible Playbook
      run: |
        touch /tmp/ec2-key
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > /tmp/ec2-key
        chmod 600 /tmp/ec2-key
        ansible-playbook -i terraform/dynamic_inventory.json ansible/provision.yml --private-key /tmp/ec2-key
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy zkEVM
      run: |
        # Deploy your zkEVM implementation.

    - name: Bridge ETH from L1 to L2
      run: |
        # Implement the bridge service to facilitate ETH bridging.

    - name: Cleanup
      run: |
        # Perform cleanup, terminate cloud resources, and stop containers when done.

# Add additional steps and configurations as needed.
