name: EVM Testnet Workflow

on:
  workflow_dispatch:
  
jobs:
  deploy-testnet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Pull Docker Images
      run: |
        docker pull 104047360514.dkr.ecr.eu-central-1.amazonaws.com/go-ethereum:latest
        docker pull 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkvem-node:latest
        docker pull 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-prover:latest
        docker pull 104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-contracts:latest

    - name: Set up Cloud Environment
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose your preferred Python version

    - name: Install Ansible
      run: pip install ansible

    - name: Download Ansible Dynamic Inventory Script
      run: |
        wget https://raw.githubusercontent.com/ansible/ansible/stable-2.9/contrib/inventory/ec2.py
        chmod +x ec2.py

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ec2.py ansible/provision.yml

    - name: Create EVM Testnet
      run: |
        # Start Ethereum nodes with the geth image and connect them to form a testnet.

    - name: Deploy zkEVM
      run: |
        # Deploy your zkEVM implementation.

    - name: Bridge ETH from L1 to L2
      run: |
        # Implement the bridge service to facilitate ETH bridging.

    - name: Cleanup
      run: |
        # Perform cleanup, terminate cloud resources, and stop containers when done.

# Add additional steps and configurations as needed.
